export const WHATSAPP_MESSAGE_LIST_REQUESTED =
  "WHATSAPP_MESSAGE_LIST_REQUESTED";
export const WHATSAPP_MESSAGE_LIST_SUCCESS = "WHATSAPP_MESSAGE_LIST_SUCCESS";
export const WHATSAPP_MESSAGE_LIST_ERROR = "WHATSAPP_MESSAGE_LIST_ERROR";
export const WHATSAPP_CONTACTS_LIST_REQUESTED =
  "WHATSAPP_CONTACTS_LIST_REQUESTED";
export const WHATSAPP_CONTACTS_LIST_SUCCESS = "WHATSAPP_CONTACTS_LIST_SUCCESS";
export const WHATSAPP_CONTACTS_LIST_ERROR = "WHATSAPP_CONTACTS_LIST_ERROR";
export const WHATSAPP_CURRENT_CONTACT_UPDATE =
  "WHATSAPP_CURRENT_CONTACT_UPDATE";
export const EMPTY_WHATSAPP_MESSAGE_LIST = "EMPTY_WHATSAPP_MESSAGE_LIST";
